### ISSUE TITLE
Relation to npm / yarn / etc?

### ISSUE THREAD

**Issue by transitive-bullshit** [zkat/pacote-old#161]
This project looks really interesting and very well done so far.

I'd love to understand a bit more about its intended use case in relation to existing package managers within the npm community. In particular, is `pacote` designed to solve a specific problem, is it an experiment, or is it intended to eventually replace the `npm` CLI?

Apologies if this is answered elsewhere, but I tried searching through the docs / issues / etc without much luck.

Thanks!

**Comment by zkat** [comment]
pacote is not a package manager and doesn't aim to be. It is just a utility to make it easier to find and fetch packages.

It's actually been part of npm itself since `npm@5.0.0` and basically replaced the old npm network infra for package lookup and download.

So basically, if you use pacote for your scripts, you're using the same code npm itself uses. It means you can use npm's cache, its settings, etc (you have to read the configuration yourself and pass it to pacote, though)

**Comment by transitive-bullshit** [comment]
Awesome -- thanks for the thorough explanation @zkat.
