### ISSUE TITLE
Normalize and standardise manifests

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#17]
pacote should normalize metadata fields to only the things the CLI might need, and standardize those across the different sources. Should also run the manifest through `normalize-package-data`.

**Comment by iarna** [comment]
Yes, do run the manifest through `normalize-package-data`, in particular, because it normalizes things like `bundleDependencies`/`bundledDependencies`.

Ok, so to the best of my knowledge the required keys are:

```
name
version
dependencies
optionalDependencies
devDependencies
bundleDependencies
peerDependencies
bin
```

Also these, which are from various places in the cache currently:

* `_resolved`, `_from` - these are where resolved and from in the shrinkwrap come from. They're also used throughout the installer.
* `_id`, `_shasum` - are added by the existing cache code.
* `_spec` - This is a `fetch-package-metadata` artifact and should be removed.

**Comment by iarna** [comment]
`normalize-package-data` also copies all of the `optionalDependencies` into `dependencies`.

**Comment by zkat** [comment]
We're currently adding `_shrinkwrap` as well (pacote-side, sometimes maybe registry-side?)

Also, the `bin` thing is also mentioned over at #18

**Comment by zkat** [comment]
Note: `_id` is not needed, but will probably get shoved in there anyway by `normalize-package-data`.
